name: "Debian 10 Buster"

on:
  push:
    branches: [ 'main' ]
    paths:
      - ".github/workflows/debian10.yml"
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, x86_64, i386]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Start Build!
        run: |
              ARCH=${{ matrix.arch }}
              case "$ARCH" in
              x86_64) ARCH=amd64 ;;
              amd64) ARCH=amd64 ;;
              aarch64) ARCH=arm64 ;;
              arm64) ARCH=arm64 ;;
              arm) ARCH=arm ;;
              i386) ARCH=386 ;;
              *)
              echo "Unsupported architecture: $ARCH"
              exit 1
              ;;
              esac
              # Fetch image manifest
              manifest=$(docker manifest inspect debian:buster)
              # Fetch image digest
              arch="$ARCH"
              digest=$(echo "$manifest" | jq -r ".manifests[] | select(.platform.architecture == \"$arch\") | .digest")
              # Pull and Export image
              docker pull "debian:buster@${digest}"
              docker export $(docker create "debian:buster@${digest}") | xz -T 0 > "$GITHUB_WORKSPACE/debian10-${{ matrix.arch }}.tar.xz"

      - name: Push to release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: debian10
          name: Debian 10 Buster
          files: |
            debian10-*.tar.xz
          preserve_order: true

  build-arm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Start Build!
        run: |
              ARCH=${{ matrix.arch }}
              case "$ARCH" in
              x86_64) ARCH=amd64 ;;
              amd64) ARCH=amd64 ;;
              aarch64) ARCH=arm64 ;;
              arm64) ARCH=arm64 ;;
              arm) ARCH=arm ;;
              i386) ARCH=386 ;;
              *)
              echo "Unsupported architecture: $ARCH"
              exit 1
              ;;
              esac
              # Fetch image manifest
              manifest=$(docker manifest inspect debian:buster)
              # Fetch image digest
              arch="$ARCH"
              digest=$(echo "$manifest" | jq -r ".manifests[] | select(.platform.architecture == \"$arch\") | select(.platform.variant == \"v7\") | .digest")
              # Pull and Export image
              docker pull "debian:buster@${digest}"
              docker export $(docker create "debian:buster@${digest}") | xz -T 0 > "$GITHUB_WORKSPACE/debian10-${{ matrix.arch }}.tar.xz"

      - name: Push to release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: debian10
          name: Debian 10 Buster
          files: |
            debian10-*.tar.xz
          preserve_order: true
