name: "Ubuntu LTS 18.04"

on:
  push:
    branches: [ 'main' ]
    paths:
      - ".github/workflows/ubuntu-lts18.yml"
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Start Build!
        run: |
              ARCH=${{ matrix.arch }}
              case "$ARCH" in
              x86_64) ARCH=amd64 ;;
              *)
              echo "Unsupported architecture: $ARCH"
              exit 1
              ;;
              esac
              # Fetch image manifest
              manifest=$(docker manifest inspect ubuntu:bionic)
              # Fetch image digest
              arch="$ARCH"
              digest=$(echo "$manifest" | jq -r ".manifests[] | select(.platform.architecture == \"$arch\") | .digest")
              # Pull and Export image
              docker pull "ubuntu:bionic@${digest}"
              docker export $(docker create "ubuntu:bionic@${digest}") | xz -T 0 > "$GITHUB_WORKSPACE/ubuntu-lts18-${{ matrix.arch }}.tar.xz"
              
      - name: Push to release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ubuntu-lts18
          name: Ubuntu LTS 18.04 Bionic Beaver
          files: |
            ubuntu-lts18-*.tar.xz
          preserve_order: true

  build-arm64:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        arch: [aarch64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Start Build!
        run: |
              ARCH=${{ matrix.arch }}
              case "$ARCH" in
              x86_64) ARCH=amd64 ;;
              amd64) ARCH=amd64 ;;
              aarch64) ARCH=arm64 ;;
              arm64) ARCH=arm64 ;;
              arm) ARCH=arm ;;
              i386) ARCH=386 ;;
              *)
              echo "Unsupported architecture: $ARCH"
              exit 1
              ;;
              esac
              # Fetch image manifest
              manifest=$(docker manifest inspect ubuntu:bionic)
              # Fetch image digest
              arch="$ARCH"
              digest=$(echo "$manifest" | jq -r ".manifests[] | select(.platform.architecture == \"$arch\") | .digest")
              # Pull and Export image
              docker pull "ubuntu:bionic@${digest}"
              docker export $(docker create "ubuntu:bionic@${digest}") | xz -T 0 > "$GITHUB_WORKSPACE/ubuntu-lts18-${{ matrix.arch }}.tar.xz"
      - name: Push to release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ubuntu-lts18
          name: Ubuntu LTS 18.04 Bionic Beaver
          files: |
            ubuntu-lts18-*.tar.xz
          preserve_order: true
          
  build-arm:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        arch: [arm]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Start Build!
        run: |
              ARCH=${{ matrix.arch }}
              # Fetch image manifest
              manifest=$(docker manifest inspect ubuntu:bionic)
              # Fetch image digest
              arch="$ARCH"
              digest=$(echo "$manifest" | jq -r ".manifests[] | select(.platform.architecture == \"$arch\") | select(.platform.variant == \"v7\") | .digest")
              # Pull and Export image
              docker pull "ubuntu:bionic@${digest}"
              docker export $(docker create "ubuntu:bionic@${digest}") | xz -T 0 > "$GITHUB_WORKSPACE/ubuntu-lts18-${{ matrix.arch }}.tar.xz"
      - name: Push to release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ubuntu-lts18
          name: Ubuntu LTS 18.04 Bionic Beaver
          files: |
            ubuntu-lts18-*.tar.xz
          preserve_order: true
