name: "Void musl"

on:
  schedule:
# Build Every Week
    - cron: "0 0 * * 0"
  push:
    branches: [ 'main' ]
    paths:
      - ".github/workflows/void-musl.yml"
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Start Build!
        run: |
              ARCH=${{ matrix.arch }}
              case "$ARCH" in
              x86_64) ARCH=amd64 ;;
              amd64) ARCH=amd64 ;;
              aarch64) ARCH=arm64 ;;
              arm64) ARCH=arm64 ;;
              arm) ARCH=arm ;;
              i386) ARCH=386 ;;
              *)
              echo "Unsupported architecture: $ARCH"
              exit 1
              ;;
              esac
              # Fetch image manifest
              manifest=$(docker manifest inspect ghcr.io/void-linux/void-musl:latest)
              # Fetch image digest
              arch="$ARCH"
              digest=$(echo "$manifest" | jq -r ".manifests[] | select(.platform.architecture == \"$arch\") | .digest")
              # Pull and Export image
              docker pull "ghcr.io/void-linux/void-musl:latest@${digest}"
              docker export $(docker create "ghcr.io/void-linux/void-musl:latest@${digest}") | xz -T 0 > "$GITHUB_WORKSPACE/void-musl-${{ matrix.arch }}.tar.xz"
              mkdir dump
              sudo tar -xJpf void-musl-${{ matrix.arch }}.tar.xz -C dump
              sudo rm void-musl-${{ matrix.arch }}.tar.xz
              
              cat <<- EOF | sudo unshare -mpf bash -e -
              rm -f "./dump/etc/resolv.conf"
              echo "nameserver 1.1.1.1" > "./dump/etc/resolv.conf"
              mount --bind /dev "./dump/dev"
              mount --bind /proc "./dump/proc"
              mount --bind /sys "./dump/sys"
              mount --bind ./dump "./dump"
              chroot "./dump" xbps-install -Syu 
              chroot "./dump" xbps-install -Sy bash util-linux
              chroot "./dump" chsh -s /bin/bash root
              EOF
              
              cd $GITHUB_WORKSPACE/dump
              sudo tar --exclude=dev/* -cpf - * | xz -9 -T0 -c > $GITHUB_WORKSPACE/void-musl-${{ matrix.arch }}.tar.xz
              sudo rm -r $GITHUB_WORKSPACE/dump
              
      - name: Push to release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: void-musl
          name: Void musl
          files: |
            void-*.tar.xz
          preserve_order: true

  build-arm64:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        arch: [aarch64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Start Build!
        run: |
              ARCH=${{ matrix.arch }}
              case "$ARCH" in
              x86_64) ARCH=amd64 ;;
              amd64) ARCH=amd64 ;;
              aarch64) ARCH=arm64 ;;
              arm64) ARCH=arm64 ;;
              arm) ARCH=arm ;;
              i386) ARCH=386 ;;
              *)
              echo "Unsupported architecture: $ARCH"
              exit 1
              ;;
              esac
              # Fetch image manifest
              manifest=$(docker manifest inspect ghcr.io/void-linux/void-musl:latest)
              # Fetch image digest
              arch="$ARCH"
              digest=$(echo "$manifest" | jq -r ".manifests[] | select(.platform.architecture == \"$arch\") | .digest")
              # Pull and Export image
              docker pull "ghcr.io/void-linux/void-musl:latest@${digest}"
              docker export $(docker create "ghcr.io/void-linux/void-musl:latest@${digest}") | xz -T 0 > "$GITHUB_WORKSPACE/void-musl-${{ matrix.arch }}.tar.xz"
              mkdir dump
              sudo tar -xJpf void-musl-${{ matrix.arch }}.tar.xz -C dump
              sudo rm void-musl-${{ matrix.arch }}.tar.xz
              
              cat <<- EOF | sudo unshare -mpf bash -e -
              rm -f "./dump/etc/resolv.conf"
              echo "nameserver 1.1.1.1" > "./dump/etc/resolv.conf"
              mount --bind /dev "./dump/dev"
              mount --bind /proc "./dump/proc"
              mount --bind /sys "./dump/sys"
              mount --bind ./dump "./dump"
              chroot "./dump" xbps-install -Syu 
              chroot "./dump" xbps-install -Sy bash util-linux
              chroot "./dump" chsh -s /bin/bash root
              EOF
              
              cd $GITHUB_WORKSPACE/dump
              sudo tar --exclude=dev/* -cpf - * | xz -9 -T0 -c > $GITHUB_WORKSPACE/void-musl-${{ matrix.arch }}.tar.xz
              sudo rm -r $GITHUB_WORKSPACE/dump
              
      - name: Push to release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: void-musl
          name: Void musl
          files: |
            void-*.tar.xz
          preserve_order: true
